---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mwstack-webhookforwarder-secret
  namespace: mwstack
spec:
  encryptedData:
    token: AgCe5sHWkHrQymiikNFUDJtsMMTufJxhAPSWKjdbGTZAvQ2OyqB+v7HFX+5eqV0D8uo3/xnaGfyX1dt0S6dIn6l7dmcha9hL3w2qeagYXt0Emshu9YEO52dteATYBYhaXuFxZyO5jzGCYttbZLhdSqHM8at+t1pnC33FJAnUdR3a8obJclLUzbKzA/4Zr2FpGzfJafvTGnHigZujxGBLgf6i1MMz81eRsmk/2m9ofESXzfjP5z1qb8bq9hsRa+2fKqEecseDMeTJlXgw0WTKvCi86Txm3GfoRs3bMwkNM9q5AWaiwKX2bEc+9fsGQ1FtRnkXlhZlh5ZA/1BcxsHqv9t6q3m08lAcAB0ybDGGA4tjAMTSTwJwGSDdRTOP4qsU0YIGA668dOGFhPF0pEq7MZhhpRP9+SWGvFWm834poJ3yb3lctTQX3aDHqdWBVX1aOJxeWWnJBaGgU/kjubGsqmp7F+cKr6EcopVVMMv2JIKFvw0/zcf1p0q7Wwdnw5EaCrul6RWyLA9OYgwXS8XgrZ/GIW0e4wONHd1+cpapoQ6vDltkSr8ee/dXIgQ78B7x4RlIZTvzUq6iJ4wciD3+vKVs7L21EZUFlbEg4bdQWSp4MET1/+UTam9FADescDIxzakQNonXEYW0d/ixVOaTvdillDII+rPFCqvZYsX2RdSA4rf9xO4I+iyxUpa5+au70RlnwdSS2295Ym7CZgxnvCeA4ut/MAJpfSCcsIMFdav+8fuIRJcuvg6HmwaA7ugpQsiPDyHcqmObvvCi90YCXLEO+NZHSXcNVeMioe9hRee7q+6F+uY29aKr9rW/zHQnsQtodvO60GP3atbsN+2UTTpoiJiJ/+0C5sCHi49ezqnWOQ==
  template:
    metadata:
      name: mwstack-webhookforwarder-secret
      namespace: mwstack
    type: Opaque
